before_script:
  - echo "Execute scripts which are required to bootstrap the application. !"

after_script:
  - echo "Clean up activity can be done here !."

cache:
  paths:
    - /root/.m2/repository

stages:
  - build
  - deploy

build:
  stage: build
  image: maven:3.6.1-jdk-12
  script:
    - mvn clean package
  tags:
    - docker

deploy_dev:
  stage: deploy
  image: ruby:2.3
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=vel-ci-api-dev --api-key=$HEROKU_API_KEY
  environment:
  #  name: dev
  #  url: https://$HEROKU_APP_NAME.herokuapp.com
  only:
    - master
  tags:
    - docker