before_script:
  - echo "Execute scripts which are required to bootstrap the application. !"

after_script:
  - echo "Clean up activity can be done here !."

cache:
  paths:
    - /root/.m2/repository

stages:
  - build
  - deploy

build:
  stage: build
  image: maven:3.6.1-jdk-12
  script:
    - mvn clean package
  artifacts:
    paths:
      - target/*.jar
  tags:
    - docker

deploy_dev:
  stage: deploy
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
  only:
    - master
  tags:
    - docker

#deploy_dev:
#  stage: deploy
#  image: ubuntu:latest
#  script:
#    - apt-get update -qy
#    - apt-get install wget curl software-properties-common -y
#    - add-apt-repository --yes ppa:rpardini/adoptopenjdk
#    - apt-get install -y adoptopenjdk-12-installer
#    - wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
#    - heroku plugins:install heroku-cli-deploy
#    - heroku deploy:jar target/*.jar --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
#  #  environment:
#  #  name: dev
#  #  url: https://$HEROKU_APP_NAME.herokuapp.com
#  only:
#    - master
#  tags:
#    - docker