spring:
  messages:
    basename: message/messages

  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration

  jackson:
    deserialization:
      fail-on-unknown-properties: false

  jpa:
    properties:
      hibernate:
        order_inserts: true
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      jdbc:
        lob:
        non_contextual_creation: true

  datasource:
    platform: mysql
    url: jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:todo}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    hikari:
      minimumIdle: 1
      maximumPoolSize: 2

springdoc:
  swagger-ui:
    path: /api-ui/swagger-ui.html
  api-docs:
    path: /api-docs

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
    cors:
      allowed-origins: *

app:
  jwt:
    signingKey: c1834380e019897956cf9b6429d77a2f0cb102173d5d1ea40a21b390a65f18b5
    expiration: 3600000
    refresh: 28800000
    defaultPw: 12345678

  security:
    secret: abc123
    expiration: 604800000
    maxLoginAttemp: 10
    hmacSecret: KvoiLoApRyPIgWRmDfiIQ3Gn9IYZJqhf

  cloudinary:
    cloud_name: ${CLOUDINARY_CLOUD_NAME:lololol}
    api_key: ${CLOUDINARY_API_KEY:123456789}
    api_secret: ${CLOUDINARY_API_SECRET:lololol123}

logging:
  level:
    org:
      apache:
        http: DEBUG
      springframework:
        web: DEBUG
